#Workflow name
name: Test Spring Boot CI/CD Pipeline
on: [push]
jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3
      #Set up JDK 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - run: ./gradlew build --no-daemon

      #Run Tests
      - name: Run Tests
        run: ./gradlew check
  #Build's job
  build:
    name: Build
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v3
      #Set up JDK 17
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - run: ./gradlew build --no-daemon
      # Build the application with Gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      #Upload the build file
      - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v3
        with:
          #Set artifact name
          name: build-artifact
          #From this path
          path: target/testspringboot-0.0.1-SNAPSHOT.jar
